// src/lib/components/DeviceToggle.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte'
  import type { DeviceMode } from '../stores/themeStore'

  export let mode: DeviceMode = 'mobile'
  const dispatch = createEventDispatcher<{ change: DeviceMode }>()

  const setMode = (value: DeviceMode) => {
    mode = value
    dispatch('change', mode)
  }
</script>

<div class="device-toggle">
  <button
    class:active={mode === 'mobile'}
    type="button"
    on:click={() => setMode('mobile')}
  >
    手机
  </button>
  <button
    class:active={mode === 'desktop'}
    type="button"
    on:click={() => setMode('desktop')}
  >
    桌面
  </button>
</div>

// src/lib/components/DeviceToggle.tsx
import { useThemeContext } from '../stores/themeContext';

function DeviceToggle() {
  const { deviceMode, setDeviceMode } = useThemeContext();

  return (
    <div className="device-toggle">
      <button className={deviceMode === 'mobile' ? 'active' : ''} type="button" onClick={() => setDeviceMode('mobile')}>
        手机
      </button>
      <button
        className={deviceMode === 'desktop' ? 'active' : ''}
        type="button"
        onClick={() => setDeviceMode('desktop')}
      >
        桌面
      </button>
    </div>
  );
}

export default DeviceToggle;
