// src/lib/components/ThemeSelector.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte'
  import type { ThemeInfo } from '../stores/themeStore'
  import type { HighlightThemeInfo } from '../utils/themes'

  export let themes: ThemeInfo[] = []
  export let activeThemeId: string | null = null
  export let highlightThemes: HighlightThemeInfo[] = []
  export let highlightTheme = 'github'

  const dispatch = createEventDispatcher<{
    theme: string
    highlight: string
  }>()

  const handleThemeChange = (event: Event) => {
    const value = (event.target as HTMLSelectElement).value
    dispatch('theme', value)
  }

  const handleHighlightChange = (event: Event) => {
    const value = (event.target as HTMLSelectElement).value
    dispatch('highlight', value)
  }
</script>

<div class="selector">
  <div class="selector__group">
    <label for="theme-select">Theme</label>
    <select id="theme-select" on:change={handleThemeChange} bind:value={activeThemeId}>
      {#if themes.length === 0}
        <option value="" disabled>No themes found</option>
      {:else}
        {#each themes as item}
          <option value={item.id}>{item.name}</option>
        {/each}
      {/if}
    </select>
  </div>

  <div class="selector__group">
    <label for="highlight-select">Highlight</label>
    <select id="highlight-select" on:change={handleHighlightChange} bind:value={highlightTheme}>
      {#each highlightThemes as item}
        <option value={item.value}>{item.label}</option>
      {/each}
    </select>
  </div>
</div>

// src/lib/components/ThemeSelector.tsx
import React, { type ChangeEventHandler } from 'react';
import { useThemeContext, type ThemeInfo } from '../stores/themeContext';
import type { HighlightThemeInfo } from '../utils/themes';

function ThemeSelector({ highlightThemes }: { highlightThemes: HighlightThemeInfo[] }) {
  const { themes, activeTheme, selectTheme, highlightTheme, setHighlightTheme } = useThemeContext();

  const handleThemeChange: ChangeEventHandler<HTMLSelectElement> = (event) => {
    const value = (event.target as HTMLSelectElement).value;
    selectTheme(value);
  };

  const handleHighlightChange: ChangeEventHandler<HTMLSelectElement> = (event) => {
    const value = (event.target as HTMLSelectElement).value;
    setHighlightTheme(value);
  };

  return (
    <div className="selector">
      <div className="selector__group">
        <label htmlFor="theme-select">Theme</label>
        <select id="theme-select" onChange={handleThemeChange} value={activeTheme?.id}>
          {themes.length === 0 && (
            <option value="" disabled>
              No themes found
            </option>
          )}
          {themes.map((item) => (
            <option value={item.id} key={item.id}>{item.name}</option>
          ))}
        </select>
      </div>

      <div className="selector__group">
        <label htmlFor="highlight-select">Highlight</label>
        <select id="highlight-select" onChange={handleHighlightChange} value={highlightTheme}>
          {highlightThemes.map((item) => (
            <option value={item.value} key={item.value}>{item.label}</option>
          ))}
        </select>
      </div>
    </div>
  );
}

export default ThemeSelector;
